### ISSUE TITLE
Mark of the champion benefitting pets?

### ISSUE THREAD

**Issue by watchyoursixx** [watchyoursixx/hunter-tbc#9]

**Comment by skinnay-dev** [comment]
Small sample of data from Djlovedrop: https://docs.google.com/spreadsheets/d/1J2OeZKrkqLUSimS3DJxLQhfyWnU8MwB2sp_UqijJRbQ/edit?usp=sharing

Tests were performed with an untalented lvl 60 hunter's cat pet attacking level 58, 59, and 60 hellboars with and without motc equipped (wearing typical gear otherwise). 

Average damage per hit on lvl 58 target, excluding glance/crit:
MotC on: 96.78
MotC off: 95.41

There should be a difference of roughly 5 base damage per hit (((150*.22)/14*2)*1.1) before armor, so it does not appear to be benefiting from the +AP to demon, but more testing would help confirm. If you want to submit more data, make sure you avoid any variance in the damage amounts, such as ferocious inspiration procs, different level/armor value enemies, armor debuffs, pet happiness level, leaving trueshot aura range, etc.

**Comment by skinnay-dev** [comment]
Did some more tests now that I'm in beta, the difference in avg dmg was similarly negligible but the other way around:

MotC on: 105.37
MotC off: 106.88

**Comment by watchyoursixx** [comment]
Based on the testing here and here #8, we can assume pet does not get AP from specific target types. This kinda makes sense because pets don't benefit from Hunter's mark RAP or from expose weakness RAP (from the hunter) and I'd assume the AP per target type is being applied in the same way "like a debuff" rather than re-calculating the hunter's RAP based on what it's targeting it only calculates it when the target is attacked. So pet would not be able to benefit from it since it's not a bonus to your RAP always, just at the moment you attack a specific type.
